#! /bin/bash

opt='--background'
opt=$opt' --recursive'
opt=$opt' --no-directories'
opt=$opt' --quota=100m'

url='ftp://ftp.marine.csiro.au/pub/IMOS/NRS/MariaIsland_3/'

echo 'wget '$opt'  '$url
wget $opt $url
