try
acorn_listing_main_netcdf_UNIX('GBR','GBR_SQL_last_update.txt')
end
try
acorn_listing_main_netcdf_UNIX('SAG','SAG_SQL_last_update.txt')
end
try
acorn_listing_main_netcdf_UNIX('PCY','PCY_SQL_last_update.txt')
end
