# conda env create --file=environment.yml
# conda env update --file=environment.yml
name: ardc_nrt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=20.0.2
  - pip:
    - -r requirements.txt
    - "git+https://github.com/aodn/python-aodntools.git"
