function aatamssattagmetadata = importAustralianTagCSV(filename)
 warning('off','stats:dataset:subsasgn:DefaultValuesAddedVariable')

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AATAMS/metadata/aatams_sattag_metadata.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/12/09 18:32:13

%% Initialize variables.
delimiter = ',';

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);



%% Create output variable
aatamssattagmetadata = dataset;
aatamssattagmetadata.pkid = dataArray{:, 1};
aatamssattagmetadata.sattag_program = dataArray{:,2};
aatamssattagmetadata.device_id = dataArray{:,3};
aatamssattagmetadata.ptt = dataArray{:, 4};
aatamssattagmetadata.body = dataArray{:, 5};
aatamssattagmetadata.device_wmo_ref = dataArray{:,6};
aatamssattagmetadata.tag_type = dataArray{:,7};
aatamssattagmetadata.common_name = dataArray{:,8};
aatamssattagmetadata.species = dataArray{:,9};
aatamssattagmetadata.release_lat = dataArray{:, 10};
aatamssattagmetadata.release_lon = dataArray{:, 11};
aatamssattagmetadata.release_site = dataArray{:,12};
aatamssattagmetadata.state_country = dataArray{:,13};
aatamssattagmetadata.release_date = dataArray{:,14};
aatamssattagmetadata.recovery_date = dataArray{:,15};
aatamssattagmetadata.age_class = dataArray{:,16};
aatamssattagmetadata.sex = dataArray{:,17};
aatamssattagmetadata.length = dataArray{:,18};
aatamssattagmetadata.girth = dataArray{:,19};
aatamssattagmetadata.estimated_mass = dataArray{:,20};
aatamssattagmetadata.actual_mass = dataArray{:,21};
aatamssattagmetadata.sample = dataArray{:,22};
aatamssattagmetadata.comment = dataArray{:,23};
aatamssattagmetadata.pi = dataArray{:,24};
aatamssattagmetadata.institution = dataArray{:,25};
aatamssattagmetadata.abstract = dataArray{:,26};
aatamssattagmetadata.opendapurl = dataArray{:,27};
aatamssattagmetadata.metadata = dataArray{:,28};

end