#! /bin/bash

#opt='--background'
opt='-o wget.log'
opt=$opt' --recursive'
opt=$opt' --no-directories'
opt=$opt' --quota=100m'


url='ftp://ftp.marine.csiro.au/pub/IMOS/NRS/'$1

echo 'wget '$opt'  '$url
wget $opt $url
