% Matlab script to select ARGO profiles that fall into Australian region (-90 to 0 lat and 90 to 180 lon)
% uses matlab-netcdf-mex 
% run on salp, data stored on katabatic (/v/hpclibrary mount on salp) 
% input --> listoffiles a list of all the argo profiles generated by "ls'"
% output --> Australia_float a list of all the selected floats and the relative meta and tech files
%             float_emii.txt a list of only the selected profiles
% paolap@utas.edu.au

'I am starting'
addpath(genpath('/usr/local/matlab-netcdf-mex'))
lat_range = [-90 0];
lon_range = [90 180];
%dir = '/v/hpclibrary/argo_csiro/csiro_rsync/dac/';
dir = '/ds/projects/argo_csiro/csiro_rsync/dac/';
! rm listoffiles
! ./listargo
! rm float_emii.txt

fid = fopen('listoffiles');
fid2 = fopen('float_emii.txt','w');

% read the file content with textscan, the result is a cell array
 A = textscan(fid, '%s');
 B = A{1,1};     % passing from the first cell array to a cell array of strings
 nfile = size(B,1);  % deriving the number of files from the cell size 
 clear A
 fclose(fid);
index(1:nfile) = 0;

 for i=1:nfile
     if (i/100 - i/100.) == 0; i; end    %
     ncfile = B{i,1};
     if (ncfile(42:46) == 'csiro') ;   % floats from CSIRO are automatically added to emii list
        index(i) = 0;
        tr_file = B{i,1};
        tr_file(2:14) = [];
        tr_file = ['/ds/projects',tr_file];
        fprintf(fid2,'%s\n',tr_file);
     else
        f = netcdf(ncfile, 'read');
        lat = f{'LATITUDE'}(:);
        lon = f{'LONGITUDE'}(:);
        latsz = size(lat,1);
        k = 1;
        while index(i) == 0 && k<=latsz
         if (lat(k) <= lat_range(2) & lat(k) >= lat_range(1)) & ...
           (lon(k) <= lon_range(2) & lon(k) >= lon_range(1))  ;
         index(i) = 1;
         end   % if range
         k=k+1;
        end  %  while
        % closing netcdf file
        close(f)
     end     % if csiro
   
 end  % end of file cycle
 
 % cleaning up
 clear i k
 
 % remove previous list of floats
 ! rm Australia_float
 
 % open new Australia_float file and add selected profiles
 fid = fopen('Australia_float','w');
 for i=1:nfile
 
     if index(i) == 1
        tr_file = B{i,1};
        tr_file(2:14) = [];
        tr_file = ['/ds/projects',tr_file];
%        pr_file = ([tr_file(41:(end-7)),'prof.nc']);
        mt_file = ([tr_file(1:(end-7)),'meta.nc']);
        tc_file = ([tr_file(1:(end-7)),'tech.nc']);
        % retrieve the float number from string
        remain = tr_file(41:end);
        pr_dir = tr_file(1:40);
        for l = 1:2
           [token, remain] = strtok(remain,'/');
           pr_dir = [pr_dir, token,'/'];
        end
        float = token;
        pr_dir = [pr_dir,'profiles/'];
        % print file names to be linked
        fprintf(fid,'%s\n',mt_file);
        fprintf(fid,'%s\n',tc_file);
        fprintf(fid,'%s\n',tr_file);
        fprintf(fid2,'%s\n',tr_file);
        clear  token remain l
     end
 end  % end of file cycle
 fclose(fid)
 fclose(fid2)
 
% copy output list of files to katabatic 
! cp Australia_float /v/hpclibrary/argo_csiro/argo_australia/.
! cp float_emii.txt /v/hpclibrary/argo_csiro/argo_australia/.
'finished!'
